version: "3"
services:
  snapserver:
    image: jaedb/snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /tmp/snapserver:/tmp
      - ./docker/snapserver.conf:/etc/snapserver.conf # Copy from snapserver-example.conf
      - ./docker/snapserver.json:/root/.config/snapserver/server.json
      - ./docker/meta_mopidy.py:/usr/share/snapserver/plug-ins/meta_mopidy.py
  mopidy:
    image: jaedb/iris
    environment:
      - PIP_PACKAGES=Mopidy-YTMusic Mopidy-Tidal Mopidy-SoundCloud Mopidy-MusicBox-Webclient
    build:
      context: .
    depends_on:
      - snapserver
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      - ./docker/data:/var/lib/mopidy/iris
      - ./docker/mopidy.conf:/config/mopidy.conf
      - /mnt/Music:/var/lib/mopidy/media
      - /tmp/snapserver:/tmp
