version: "3"
services:
  snapserver:
    image: jaedb/snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /tmp/snapserver:/tmp
      - ./docker/snapserver.conf:/etc/snapserver.conf
  mopidy:
    image: jaedb/iris
    environment:
      - PIP_PACKAGES="Mopidy-SoundCloud Mopidy-MusicBox-Webclient"
    build:
      context: .
    depends_on:
      - snapserver
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      # Uncomment these lines to use a host-managed development build
      #- ./mopidy_iris:/iris/mopidy_iris
      #- ./IRIS_VERSION:/iris/IRIS_VERSION
      - ./docker/data:/var/lib/mopidy/iris
      - ./docker/mopidy.conf:/config/mopidy.conf
      - /mnt/Music:/var/lib/mopidy/media
      - /tmp/snapserver:/tmp
