name: I have a question
description: Get help with using Iris
body:
  - type: markdown
    attributes:
      value: |
       STOP! QUESTIONS DON'T BELONG IN THE REPOSITORY ISSUE TRACKER.
       Please instead use the [Mopidy Discourse](https://discourse.mopidy.com/) forum.
